### POST request to create patient
POST http://localhost:4000/patient
Content-Type: application/json

{
  "name": "Rohit Kumar",
  "email": "rohit@gmail.com",
  "address": "123 main street",
  "dateOfBirth": "2000-10-15",
  "registrationDate": "2025-11-17"
}
###